# ==================
#
# Channels to broadcast messages to.
#
# prefix:       The prefix in chat
# nameColor:   The color of the usernames from Discord
# nameFormat:  The format of names. "%s" will be replaced with the discord name
# text_color:   The color of the message
# server:       The server to listen on
# channel:      The channel to listen on
# twoWay:         True to send messages back to Discord
# joins:        True to send player joins/quits back to discord
# deaths:       True to send player deaths back to discord
#
# ===================
channels:
  default:
    prefix: ''
    name_color: "WHITE"
    name_format: "<%s> "
    text_color: "WHITE"
    server: "000000000"
    channel: "0000000000"
    twoWay: true
    joins: false
    deaths: true

# ===========
#
# Connection to the redis server for incoming message relaying
# If disabled, an API token MUST be specified
#
# ===========
redis:
  enabled: false
  host: localhost
  port: 6379
  password: ''

# ========
#
# token: The token for the Discord robot if the robot is operating in standalone mode (redis.enabled = false)
# owner: The Discord id of the owner of the robot
#
# ========
bot:
  token: ''
  owner: '000000000'